### ISSUE TITLE
Playlist files shuffle

### ISSUE THREAD

**Issue by AlexanderKosianchuk** [rtv-group/planner#6]
On playlist update page add 2 buttons:
- shuffle
- random on request

**Comment by Evgenijisaev** [comment]
1. Increase width of the shuffle button
2. Add refresh icon on button  <span class="glyphicon glyphicon-refresh"></span>
![57](https://user-images.githubusercontent.com/32486209/31451488-eada1916-aeb4-11e7-935c-2c778d8bbe46.jpg)
3. Do not display a shuffle button if the playlist is empty
![58](https://user-images.githubusercontent.com/32486209/31451689-6c029f54-aeb5-11e7-8027-ba7dc08976da.jpg)
